frontend:
	bash components/frontend.sh
cart:
	bash components/cart.sh

mongodb:
	bash components/mongodb.sh

user:
	bash components/user.sh

catalogue:
	bash components/catalogue.sh

redis:
	bash components/redis.sh